apiVersion: v1
kind: Service
metadata:
  name: grpc-client
  labels:
    app: grpc-client
spec:
  ports:
    - port: 3030
      nodePort: 30330
      targetPort: http-port
      protocol: TCP
  selector:
    app: grpc-client
  type: LoadBalancer