apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
  labels:
    app: grpc-client
spec:
  ports:
    - port: 30330
      nodePort: 30330
      targetPort: http-port
      protocol: TCP
  selector:
    app: grpc-client
  type: NodePort