apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: counter
  type: NodePort