apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter

spec:
  containers:
    - name: counter-demo
      image: nitirajrathore/nodeserver-with-counter
      ports:
      - name: nodejs-port
        containerPort: 3000

  nodeSelector:
    hardware: high-spec